- Capability:
  - Name: Rhyme
    Description: Get one or more lines from a counting rhyme
    Parameter:
    - Name: Number
      Description: The number of lines to get
      Default: 1
  Applicability:
  - Priotity: 100
    ModelFilter:
    - TrueFilter:
        {}
