ActionHandlers:
  ActionHandler:
  - URL: tcp://127.0.0.1:7289
    SubscribeURL: ''
    CapabilityXML: /opt/autopilot/conf/pyactionhandler/WinRMActionHandler.xml
    RequestTimeout: 60
  - URL: tcp://127.0.0.1:7290
    SubscribeURL: ''
    CapabilityXML: /opt/autopilot/conf/pyactionhandler/AyehuActionHandler.xml
    RequestTimeout: 60
  - URL: tcp://127.0.0.1:7291
    SubscribeURL: ''
    CapabilityXML: /opt/autopilot/conf/pyactionhandler/CountingRhymeActionHandler.xml
    RequestTimeout: 60
