- Capability:
  - Name: ExecuteWorkflow
    Description: Execute an Ayehu Workflow
    Parameter:
    - Name: Command
      Mandatory: true
      Description: The TaskKeywords and Parameters
    - Name: Ticket
      Mandatory: true
      Description: The ticket id from ServiceNow
    - Name: Hostname
      Description: The name of the target machine
    - Name: ServiceAccount
      Default: ${ServiceAccount}
      Description: The user account to use for accessing the machine
    - Name: CustomerID
      Default: ${CustomerID}
      Description: The CustomerID from the MARS model
    - Name: Classification
      Default: ${MachineClass}
      Description: The classification of the target machine
  Applicability:
  - Priority: 100
    ModelFilter:
    - And:
      - Var:
          Name: NodeType
          Mode: string
          Value: Machine
      - Var:
          Name: ServiceAccount
          Mode: exists
